endPoint: 192.168.131.24:9910
# endpoint: 127.0.0.1:9910 
accessKeyId: 321
secretAccessKey: 123
# 本地文件存储地址
# local_file: D:\vscode\example\data
uploadDir: /opt/data/shitu
bucketName: shitu
# seconds
accessExpires: 3600